# Generated by Django 5.2.4 on 2025-07-29 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup",
            old_name="pass1",
            new_name="password",
        ),
    ]
