# Generated by Django 5.2.4 on 2025-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0002_rename_pass1_signup_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup",
            old_name="password",
            new_name="pass1",
        ),
        migrations.AddField(
            model_name="login",
            name="username",
            field=models.CharField(default="guest", max_length=50),
            preserve_default=False,
        ),
    ]
