# Generated by Django 5.2.4 on 2025-07-30 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0003_rename_password_signup_pass1_login_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup",
            old_name="pass1",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="signup",
            old_name="pass2",
            new_name="password2",
        ),
    ]
