# Generated by Django 5.2.4 on 2025-07-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0006_borrow_delete_borrowedbook"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
        migrations.AlterField(
            model_name="signup",
            name="phone_num",
            field=models.BigIntegerField(),
        ),
    ]
