# Generated by Django 5.2.4 on 2025-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0007_delete_login_alter_signup_phone_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.CharField(default="default", max_length=500),
            preserve_default=False,
        ),
    ]
