# Generated by Django 5.2.4 on 2025-08-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0009_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="App.book",
            ),
        ),
    ]
